class App {
  constructor
  async runner() {
    try {
    } catch (error) {
      if (error) {
        //
      }
    }
  }
}

async () => {};

process.on("uncaughtException", function (err) {
  console.log("Caught exception: " + err);
});
